name: Continuos integration

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-18.04
    env:
      DJANGO_SETTINGS_MODULE: config.settings.ci
      SECRET_KEY: testsci
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Installing dependencies
        run: pip install -r requirements/ci.txt
      - name: Running tests and Coverage
        run: make coverage
