name: Deploy app

on:
  push:
    - master
  release:
    types:
      - created

jobs:
  deploy:
    name: Deploy to heroku
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}